### ISSUE TITLE
Higor dev - Implementação da Funcionalidade "Gerar PDF" (Entrega 4) e Regra de Negocio que contabiliza PDFs Gerados (Entrega 3)

### ISSUE THREAD

**Issue by higucavalcanti** [netrometro/upe-2023-2-equipe-a#14]
#### Description
Com o sistema funcionando, você deve gerar um PDF da questão escolhida e tambem será contabilizado quantos PDFs foram Gerados

#### Screenshots
Não há

#### Files
C:\Users\caval\OneDrive\Área de Trabalho\Gerencia de Configuração\upe-2023-2-equipe-a\frontend\src\componentes\Questoes\QuestaoList.jsx

#### To Reproduce
Não há sinalização de possiveis bug.

#### Tasks
- [x] Task 1: criei mudaças de estados e efeitos.
- [x] Task 2: criei funções para comportar a geração de PDFs e contabilização dessa geração
- [x] Task 3: criar o botão e integrá-lo junto ao código de listagem de questões

#### Capturas de Tela
![Captura de tela 2024-03-05 095130](https://github.com/netrometro/upe-2023-2-equipe-a/assets/126099075/0b234c09-8cbd-414d-9d26-da6e1e104a3e)
![Captura de tela 2024-03-05 095152](https://github.com/netrometro/upe-2023-2-equipe-a/assets/126099075/c4dc9692-0f8b-43a0-9ef5-d64890b8e5a0)
![Captura de tela 2024-03-05 095211](https://github.com/netrometro/upe-2023-2-equipe-a/assets/126099075/c9833822-3104-4b74-a6fd-27d91131ee4c)
