### ISSUE TITLE
Task 3: Implementação de Regra de Negocio - Deleção/Remoção de uma questão a partir da lista de questões presente.

### ISSUE THREAD

**Issue by antoniosereno95** [netrometro/upe-2023-2-equipe-a#8]
#### Description
Com o sistema funcionando, você deve criar a funcionalidade de deletar uma questão utilizando um botão dentro do módulo de listagem de questões.

#### Screenshots
Não há

#### Files
C:\Users\anton\OneDrive\Documentos\GitHub\upe-2023-2-equipe-a\frontend\src\componentes\Questoes\QuestaoList.jsx

e

C:\Users\anton\OneDrive\Documentos\GitHub\upe-2023-2-equipe-a\backend\src\routes.js

#### To Reproduce
Não há sinalização de possiveis bug.

#### Tasks
- [x] Task 1: criar a rota no backend para deletar uma questão
- [x] Task 2: adicionar as funções necessárias para que a funcionalidade funcione
- [x] Task 3: criar o botão e integrá-lo junto ao código de listagem de questões

**Comment by antoniosereno95** [comment]
Issue resolvida no momento em sala de aula das 7:30 as 10:00h. Anexo vao alguns prints da soluçao proposta por mim para tal issue
![Captura de tela 2024-02-27 102452](https://github.com/netrometro/upe-2023-2-equipe-a/assets/60446351/e321fcc2-c222-4857-95d5-6ab6f1150492)
![Captura de tela 2024-02-27 102458](https://github.com/netrometro/upe-2023-2-equipe-a/assets/60446351/a3113335-12ef-44c4-8eb9-af47a643e229)
![Captura de tela 2024-02-27 102520](https://github.com/netrometro/upe-2023-2-equipe-a/assets/60446351/337a0139-891e-44f1-b430-2f5260575c0a)
![Captura de tela 2024-02-27 102538](https://github.com/netrometro/upe-2023-2-equipe-a/assets/60446351/e40b0ec4-b44b-4fb6-8b7d-578fae0d7061)
![Captura de tela 2024-02-27 102627](https://github.com/netrometro/upe-2023-2-equipe-a/assets/60446351/d469fb59-5bda-47ca-b793-4b49ab6635fc)

**Comment by antoniosereno95** [comment]
Fechando o issue ja que ele ja foi solucionado.
