### ISSUE TITLE
Task 4: Implementação do compartilhamento via Email - Enviar/Compartilhar uma Questao, a partir da listagem, via Email.

### ISSUE THREAD

**Issue by antoniosereno95** [netrometro/upe-2023-2-equipe-a#9]
#### Description
Com o sistema funcionando, você deve criar a funcionalidade de compartilhar uma questão, via email, utilizando um botão e um modal de confirmação dentro do módulo de listagem de questões.

#### Screenshots
Não há

#### Files
C:\Users\anton\OneDrive\Documentos\GitHub\upe-2023-2-equipe-a\frontend\src\componentes\Questoes\QuestaoList.jsx

e

C:\Users\anton\OneDrive\Documentos\GitHub\Fork de Ewerton\upe-2023-2-equipe-a\backend\src\server.js

#### To Reproduce
Não há sinalização de possiveis bug.

#### Tasks
- [x] Task 1: criar a rota no backend para envio via email de uma questão
- [x] Task 2: adicionar as funções necessárias para que a funcionalidade funcione
- [x] Task 3: criar o botão e integrá-lo junto ao código de listagem de questões
- [x] Task 4: criar o modal e integrá-lo junto ao código de listagem de questões

**Comment by antoniosereno95** [comment]
A task foi resolvida com sucesso trazendo valor para o usuario ao adicionar uma nova funcionalidade a ser utilizada.

A seguir vao alguns prints no codigo e testes efetuados com a funcionalidade de compartilhamento via emial.
![Captura de tela 2024-03-01 180627](https://github.com/netrometro/upe-2023-2-equipe-a/assets/60446351/5606d45c-fc1f-44fe-9dac-d7d8341a3c06)
![Captura de tela 2024-03-01 180638](https://github.com/netrometro/upe-2023-2-equipe-a/assets/60446351/ea09a231-e79d-4f13-aa98-c1c4348259bd)
![Captura de tela 2024-03-01 181726](https://github.com/netrometro/upe-2023-2-equipe-a/assets/60446351/2651e03c-01b3-490d-93ca-685deab2fd65)
![Captura de tela 2024-03-01 181901](https://github.com/netrometro/upe-2023-2-equipe-a/assets/60446351/56fbfd92-8f2a-4dae-a8e8-cdbe4806aeff)
![Captura de tela 2024-03-01 181911](https://github.com/netrometro/upe-2023-2-equipe-a/assets/60446351/e3c3b1c7-e876-46b4-a720-0ffd415faba3)
![Captura de tela 2024-03-01 183250](https://github.com/netrometro/upe-2023-2-equipe-a/assets/60446351/a1f3dfac-1dac-4bfd-b27f-2ae957ddcb1e)
![Captura de tela 2024-03-01 183259](https://github.com/netrometro/upe-2023-2-equipe-a/assets/60446351/d5391ba1-e521-4600-adf3-a27bf7466a69)
![Captura de tela 2024-03-01 183320](https://github.com/netrometro/upe-2023-2-equipe-a/assets/60446351/7c375258-f2cc-435f-900f-fd46419ce4b6)
![Captura de tela 2024-03-01 183331](https://github.com/netrometro/upe-2023-2-equipe-a/assets/60446351/788e80f9-dd27-48d6-a012-9d7e13d8f527)
![Captura de tela 2024-03-01 183340](https://github.com/netrometro/upe-2023-2-equipe-a/assets/60446351/8130bd48-2b4a-421c-9a73-82194ebb0554)
![Captura de tela 2024-03-01 183348](https://github.com/netrometro/upe-2023-2-equipe-a/assets/60446351/c8a5511a-dabf-4ca8-a5d8-9d199dbcc602)

**Comment by antoniosereno95** [comment]
Fechando o Issues com sucesso.

**Comment by antoniosereno95** [comment]
REabri para enviar mais prints dos testes agora com um email diferente do meu universitario
![Captura de tela 2024-03-01 185921](https://github.com/netrometro/upe-2023-2-equipe-a/assets/60446351/0b1f4ead-55c2-42e3-a310-c00a52f975f7)
![Captura de tela 2024-03-01 185930](https://github.com/netrometro/upe-2023-2-equipe-a/assets/60446351/0e1e3671-b8fb-492a-9999-0e61e399a6fe)
